# Generated by Django 5.1.5 on 2025-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useRole', models.CharField(default='client', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
