# Generated by Django 5.1.5 on 2025-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0002_customuser_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='useRole',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
