# Generated by Django 5.1.5 on 2025-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0004_userrole_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to',
            name='TypeTO',
            field=models.CharField(max_length=255),
        ),
    ]
