# Generated by Django 5.1.5 on 2025-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0005_alter_to_typeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelEngine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelLeadingBridge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelManagedBridge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelTransmission',
            field=models.CharField(max_length=100),
        ),
    ]
