# Generated by Django 5.1.5 on 2025-01-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0006_alter_machine_model_alter_machine_modelengine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_model', to='silantapp.referencemodel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelEngine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_modelEngine', to='silantapp.referencemodel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelLeadingBridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_modelLeadingBridge', to='silantapp.referencemodel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelManagedBridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_modelManagedBridge', to='silantapp.referencemodel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelTransmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_modelTransmission', to='silantapp.referencemodel'),
        ),
        migrations.AlterField(
            model_name='to',
            name='TypeTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos', to='silantapp.maintenancetype'),
        ),
    ]
