# Generated by Django 5.1.5 on 2025-01-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantapp', '0007_alter_machine_model_alter_machine_modelengine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='dataReclamation',
            new_name='dateReclamation',
        ),
    ]
